### ISSUE TITLE
Need advice on the training of autoencoder

### ISSUE THREAD

**Issue by JiankunW** [sihyun-yu/PVDM#5]
Hey, I trained the autoencoder with default configurations on 5 GPUs, 1 batch per GPU, but it has not converged even after 190k iterations (over 1 day). I would like to know the expected number of iterations it would take for the autoencoder to converge with default settings. 

Also, should I continue training the model, or are there any other suggestions to help it converge faster?

![image](https://user-images.githubusercontent.com/68488951/224475205-717b8b48-8575-4339-8131-c815fcae85b1.png)

Thank you,
Jiankun

**Comment by sihyun-yu** [comment]
Hi,

it's quite difficult to say the number of iterations to be converged with, because it depends a lot on the datasets that you use for training. My personal experience was that 250K iteration is enough for most datasets. Moreover, you should early-stop the model in the case of fine-tuning autoencoder with adversarial loss; I'm still not sure why it suddenly diverges, but it is likely to be unstable and often diverges suddenly.

Please don't hesitate to ask any questions if you have.

**Comment by JunyaoHu** [comment]
Hello, I would like to ask you this picture is the first stage of training ae or the second stage (gan)? @JiankunW

**Comment by JiankunW** [comment]
> Hello, I would like to ask you this picture is the first stage of training ae or the second stage (gan)? @JiankunW 

First stage.
